#ifndef CONFIG_USER_H
#define CONFIG_USER_H

// #include "quantum.h"
#include "../../config.h"

#undef RETRO_TAPPING
#undef TAPPING_TERM
#undef PERMISSIVE_HOLD
#define TAPPING_TERM 250
// #define RETRO_TAPPING
// #define PERMISSIVE_HOLD

#undef  IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT
#undef PREVENT_STUCK_MODIFIERS
#define PREVENT_STUCK_MODIFIERS

#undef  LED_BRIGHTNESS_DEFAULT
#define LED_BRIGHTNESS_DEFAULT (LED_BRIGHTNESS_LO)

#endif
